name: Application

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: "recursive"

            - name: Build
              run: |
                  corepack enable
                  yarn --no-immutable
                  yarn build

    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: "recursive"

            - name: Lint
              run: |
                  corepack enable
                  yarn --no-immutable
                  yarn lint
